events { }
http {
    upstream servidores {
        ip_hash; # para responder segur la IP 
        # servicios dentro del docker-compose
        server servidor1:5000 weight=6;
        server servidor2:5000 weight=3;
        server servidor3:5000 weight=1; 
    }  

    server {
        listen 80;
        location / {
            proxy_pass http://servidores;
        }
    }
    
}