events { }
http {
    upstream servidores {
        # Round Robin: Blanceador de carga secuencial
        server nodo1:5000;
        server nodo2:5000;

        # Weighted Load: Blanceador de carga por peso
        # server nodo1:5000 weight=6;
        # server nodo2:5000 weight=4;

        # IP Hash: Blanceador de carga por persistencia de sesion
        # ip_hash;
        # server nodo1:5000;
        # server nodo2:5000;
    }  

    server {
        listen 80;
        location / {
            proxy_pass http://servidores;
        }
    }
}