# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: conversor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'conversor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63onversor.proto\"\x1c\n\nparametros\x12\x0e\n\x06temp_1\x18\x01 \x01(\x02\"\x1f\n\tresultado\x12\x12\n\nconversion\x18\x01 \x01(\x02\x32O\n\tConversor\x12 \n\x05\x43_a_F\x12\x0b.parametros\x1a\n.resultado\x12 \n\x05\x46_a_C\x12\x0b.parametros\x1a\n.resultadob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'conversor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PARAMETROS']._serialized_start=19
  _globals['_PARAMETROS']._serialized_end=47
  _globals['_RESULTADO']._serialized_start=49
  _globals['_RESULTADO']._serialized_end=80
  _globals['_CONVERSOR']._serialized_start=82
  _globals['_CONVERSOR']._serialized_end=161
# @@protoc_insertion_point(module_scope)
