# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import conversor_pb2 as conversor__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in conversor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConversorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.C_a_F = channel.unary_unary(
                '/Conversor/C_a_F',
                request_serializer=conversor__pb2.parametros.SerializeToString,
                response_deserializer=conversor__pb2.resultado.FromString,
                _registered_method=True)
        self.F_a_C = channel.unary_unary(
                '/Conversor/F_a_C',
                request_serializer=conversor__pb2.parametros.SerializeToString,
                response_deserializer=conversor__pb2.resultado.FromString,
                _registered_method=True)


class ConversorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def C_a_F(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def F_a_C(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConversorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'C_a_F': grpc.unary_unary_rpc_method_handler(
                    servicer.C_a_F,
                    request_deserializer=conversor__pb2.parametros.FromString,
                    response_serializer=conversor__pb2.resultado.SerializeToString,
            ),
            'F_a_C': grpc.unary_unary_rpc_method_handler(
                    servicer.F_a_C,
                    request_deserializer=conversor__pb2.parametros.FromString,
                    response_serializer=conversor__pb2.resultado.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Conversor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Conversor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Conversor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def C_a_F(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Conversor/C_a_F',
            conversor__pb2.parametros.SerializeToString,
            conversor__pb2.resultado.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def F_a_C(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Conversor/F_a_C',
            conversor__pb2.parametros.SerializeToString,
            conversor__pb2.resultado.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
