version: '3.8'

services:
  calculadora:
    build:
      context: ./calculadora
      dockerfile: Dockerfile
    container_name: calculadora
    ports:
      - "5000:5000" 
    depends_on:
      - suma
      - resta
      - multiplicacion
      - division
    networks:
      - red_calculadora

  suma:
    build:
      context: ./suma
      dockerfile: Dockerfile
    container_name: suma
    networks:
      - red_calculadora

  resta:
    build:
      context: ./resta
      dockerfile: Dockerfile 
    container_name: resta
    networks:
      - red_calculadora
  
  multiplicacion:
    build:
      context: ./multiplicacion
      dockerfile: Dockerfile
    container_name: multiplicacion
    networks:
      - red_calculadora
  
  division:
    build:
      context: ./division
      dockerfile: Dockerfile
    container_name: division
    networks:
      - red_calculadora

networks:
  red_calculadora:
    driver: bridge