# Imagen base con Python 3.9
FROM python:3.9
# Define el directorio de trabajo dentro del contenedor
WORKDIR /app
# Copia todos los archivos de tu proyecto al contenedor
COPY . /app
# Comando que ejecuta el flujo completo Map → Reduce
CMD ["bash"]