version: '3'

services:

  # --- BASES DE DATOS ---
  mysql_principal:
    container_name: Maestro
    image: mysql:8.0
    ports: 
     - 3306:3306
    command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=replica 
    environment:
      MYSQL_ROOT_PASSWORD: root  
      MYSQL_DATABASE: replica
    volumes:
      - master_data:/var/lib/mysql
  
  mysql_secundario:
    container_name: Esclavo
    image: mysql:8.0
    ports: 
     - 3307:3306
    command: --server-id=2 --log-bin=mysql-bin --binlog-do-db=replica 
    environment:
      MYSQL_ROOT_PASSWORD: root  
      MYSQL_DATABASE: replica
    volumes:
      - slave_data:/var/lib/mysql

  # --- PHPMYADMIN ---
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    ports:
      - 8081:80  # <-- Puerto cambiado a 8081 para no chocar con NGINX
    environment:
      PMA_HOSTS: "mysql_principal, mysql_secundario"
      PMA_ARBITRARY: 1 

  # --- NODOS DE APLICACIÓN ---
  nodo1:
    build:
      context: ./aplicacion
      dockerfile: Dockerfile
    container_name: Nodo1
    restart: on-failure  # <-- Añadido para dar tiempo a MySQL de iniciar
    environment:
      - DB_HOST=mysql_principal
    ports:
      - 5001:5000
    depends_on:
      - mysql_principal

  nodo2:
    build:
      context: ./aplicacion
      dockerfile: Dockerfile
    container_name: Nodo2
    restart: on-failure  # <-- Añadido para dar tiempo a MySQL de iniciar
    environment:
      - DB_HOST=mysql_secundario
    ports:
      - 5002:5000
    depends_on:
      - mysql_secundario

  # --- BALANCEADOR DE CARGA ---
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: Balanceador
    ports:
      - 8080:80
    depends_on:
      - nodo1
      - nodo2

volumes:
  master_data:
  slave_data: