# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculadora.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calculadora.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x61lculadora.proto\"\"\n\nparametros\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x16\n\tresultado\x12\t\n\x01r\x18\x01 \x01(\x05\x32\x9e\x01\n\x0b\x43\x61lculadora\x12 \n\x05Sumar\x12\x0b.parametros\x1a\n.resultado\x12!\n\x06Restar\x12\x0b.parametros\x1a\n.resultado\x12&\n\x0bMultiplicar\x12\x0b.parametros\x1a\n.resultado\x12\"\n\x07\x44ividir\x12\x0b.parametros\x1a\n.resultadob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculadora_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PARAMETROS']._serialized_start=21
  _globals['_PARAMETROS']._serialized_end=55
  _globals['_RESULTADO']._serialized_start=57
  _globals['_RESULTADO']._serialized_end=79
  _globals['_CALCULADORA']._serialized_start=82
  _globals['_CALCULADORA']._serialized_end=240
# @@protoc_insertion_point(module_scope)
